### ISSUE TITLE
Java运行报错

### ISSUE THREAD

**Issue by idealspark** [aliyunvideo/AliRtcAppServer#1]
`
Exception in thread "Thread-2" java.lang.NoSuchMethodError: org.json.JSONArray.iterator()Ljava/util/Iterator;
	at com.aliyuncs.regions.LocalEndpointResolver.<init>(LocalEndpointResolver.java:39)
	at com.aliyuncs.profile.DefaultProfile.<init>(DefaultProfile.java:72)
	at com.aliyuncs.profile.DefaultProfile.getProfile(DefaultProfile.java:209)
	at com.ebaolife.asst.video.App.createChannel(App.java:110)
	at com.ebaolife.asst.video.App.access$300(App.java:26)
	at com.ebaolife.asst.video.App$LoginHandler.handle(App.java:196)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:83)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:82)
	at sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:675)
	at com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:79)
	at sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:647)
	at sun.net.httpserver.ServerImpl$DefaultExecutor.execute(ServerImpl.java:158)
	at sun.net.httpserver.ServerImpl$Dispatcher.handle(ServerImpl.java:431)
	at sun.net.httpserver.ServerImpl$Dispatcher.run(ServerImpl.java:396)
	at java.lang.Thread.run(Thread.java:745)
`

**Comment by xiaodouyaer** [comment]
运行起来后，访问地址404，仅仅开通了RTC服务，并没有买套餐
